apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    app: coordination-apiserver
  name: v1.coordination.k8s.io
spec:
  group: coordination.k8s.io
  groupPriorityMinimum: 16200
  version: v1
  versionPriority: 15
  service:
    name: coordination-apiserver
    namespace: kube-system
  insecureSkipTLSVerify: true
