apiVersion: v1
kind: Service
metadata:
  name: coordination-apiserver
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: coordination-apiserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coordination-apiserver
  name: coordination-apiserver
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordination-apiserver
  template:
    metadata:
      labels:
        app: coordination-apiserver
    spec:
      containers:
      - image: ghcr.io/wzshiming/coordination-apiserver:v0.0.1
        name: coordination-apiserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /livez
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /readyz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 10
          timeoutSeconds: 5
