apiVersion: v1
kind: Service
metadata:
  name: coordination-apiserver
  namespace: kube-system
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: coordination-apiserver
  # This is required to prevent control plane failures during updates when leases become temporarily unavailable
  publishNotReadyAddresses: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coordination-apiserver
  name: coordination-apiserver
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordination-apiserver
  template:
    metadata:
      labels:
        app: coordination-apiserver
    spec:
      terminationGracePeriodSeconds: 40
      preemptionPolicy: PreemptLowerPriority
      priority: 2000000000
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      automountServiceAccountToken: false
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
      - image: ghcr.io/wzshiming/coordination-apiserver:v0.0.3
        name: coordination-apiserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 443
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /livez
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /readyz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 5
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /readyz
            port: 443
            scheme: HTTPS
          initialDelaySeconds: 1
          periodSeconds: 2
          timeoutSeconds: 5
